name: Docker Build & Publish to github packages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker Image ğŸ—ï¸
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx ğŸš€
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry ğŸš¢
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ğŸ—ï¸
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms:
            - linux/amd64
            - linux/arm64
          file: ./Dockerfile
          push: true
          tags: ghcr.io/pollak-projects/pollakecho-bot/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # triggerUpdate:
  #   name: Trigger Update ğŸ”„
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Call Webhook
  #       uses: distributhor/workflow-webhook@v3
  #       with:
  #         webhook_url: ${{ secrets.WEBHOOK_URL }}
